### ISSUE TITLE
globus_gsi_cred_verify_cert_chain() fails with voms proxy and openssl-1.1

### ISSUE THREAD

**Issue by DrDaveD** [globus/globus-toolkit#115]
We have a CernVM-FileSystem plugin that we call "cvmfs-x509-helper" that calls globus_gsi_cred_verify_cert_chain() on VOMS proxies, and it is failing on Debian 9 with openssl-1.1.  I was able to reproduce the problem by using the included grid-cert-diagnostics tool because it uses the same function.  If you just pass the voms proxy in the -c option, and make sure that X509_CERT_DIR includes the CA and CRLs for the underlying cert, a portion of the output looks like this:
```
Checking Certificate
    ====================
    Checking cert at /tmp/x509up_u501... ok
    Checking Certificate Subject... "/DC=org/DC=opensciencegrid/O=Open Science G
rid/OU=People/CN=Dave Dykstra 508/CN=589154482/CN=872617888"
Checking cert... ok
Checking that certificate contains an RSA key... ok
Checking certificate trust chain... failed
    globus_credential: Error verifying credential: Failed to verify credential
    globus_gsi_callback_module: Could not verify credential
    globus_gsi_callback_module: Could not verify credential
    globus_gsi_callback_module: Invalid CRL: Couldn't get the issuer certificate of the CRL with subject: /DC=org/DC=cilogon/C=US/O=CILogon/CN=CILogon OSG
```

I can repeat it on EL7 using @msalle's [segfault_test.zip](/globus/globus-toolkit/files/687223/segfault_test.zip) from #87, updated with GTPKG=globus_toolkit-6.0.1506371041 and OPENSSLPKG=openssl-1.1.0f.

I did some digging into it with gdb and believe I know what the problem is but don't know how to fix it.   In gdb I noticed in X509_STORE_CTX_get1_issuer() that ctx->ctx->check_issued was set to a globus
function, but X509_STORE_CTX_get1_issuer used ctx->check_issued. So with gdb I copied up the globus function to ctx->check_issued, and it succeeded.  The problem is that there is no X509_STORE_CTX_set_check_issued() function in openssl-1.1, and unlike in openssl-1.1 the ctx->issued structure element is not defined in an accessible header file.  @ellert had already noticed the lack of X509_STORE_CTX_set_check_issued in this [debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829272).  I think the only thing to do is to restructure the code so that the check_issued function has to be set before the X509_STORE_CTX is created from the X509_STORE.

This is a high priority problem for @bbockelm and I on the Open Science Grid, and it would sure be good if there was some way to fix it quickly or even better for us to work around it in the calling code somehow.

**Comment by msalle** [comment]
Hi,
just to further clarify Dave's point, that the problem is with the order of calling X509_STORE_CTX_init() (https://github.com/globus/globus-toolkit/blob/globus_6_branch/gsi/credential/source/library/globus_gsi_cred_handle.c#L1749) before X509_STORE_set_check_issued() (https://github.com/globus/globus-toolkit/blob/globus_6_branch/gsi/credential/source/library/globus_gsi_cred_handle.c#L1758).
Simply reversing that order should probably fix the problem. This is clear from looking at the definition of X509_STORE_CTX_init() (https://github.com/openssl/openssl/blob/OpenSSL_1_1_0-stable/crypto/x509/x509_vfy.c#L2257-L2260): the X509_STORE_CTX has its own check_issued, and doesn't use the one from its embedded X509_STORE object.
